<?php

//Arrays for assorted select lists on html pages

//States Array
$states = array('' => 'Select',
'AL' => 'Alabama', 'AK' => 'Alaska', 
'AZ' => 'Arizona', 'AR' => 'Arkansas', 
'CA' => 'California', 'CO' => 'Colorado', 
'CT' => 'Connecticut', 'DE' => 'Delaware', 
'DC' => 'District Of Columbia', 'FL' => 'Florida', 
'GA' => 'Georgia', 'HI' => 'Hawaii', 
'ID' => 'Idaho', 'IL' => 'Illinois', 
'IN' => 'Indiana', 'IA' => 'Iowa', 
'KS' => 'Kansas', 'KY' => 'Kentucky', 
'LA' => 'Louisiana', 'ME' => 'Maine', 
'MD' => 'Maryland', 'MA' => 'Massachusetts', 
'MI' => 'Michigan', 'MN' => 'Minnesota', 
'MS' => 'Mississippi', 'MO' => 'Missouri', 
'MT' => 'Montana', 'NE' => 'Nebraska', 
'NV' => 'Nevada', 'NH' => 'New Hampshire', 
'NJ' => 'New Jersey', 'NM' => 'New Mexico', 
'NY' => 'New York', 'NC' => 'North Carolina', 
'ND' => 'North Dakota', 'OH' => 'Ohio', 
'OK' => 'Oklahoma', 'OR' => 'Oregon', 
'PA' => 'Pennsylvania', 'RI' => 'Rhode Island', 
'SC' => 'South Carolina', 'SD' => 'South Dakota', 
'TN' => 'Tennessee', 'TX' => 'Texas', 
'UT' => 'Utah', 'VT' => 'Vermont', 
'VA' => 'Virginia', 'WA' => 'Washington', 
'WV' => 'West Virginia', 'WI' => 'Wisconsin', 
'WY' => 'Wyoming');

$americaTimeZones = array(
  '' => 'Select',
  'America/New_York'=>'Eastern', 
  'America/Chicago'=>'Central', 
  'America/Boise'=>'Mountain', 
  'America/Phoenix'=>'Arizona Mountain', 
  'America/Los_Angeles'=>'Pacific', 
  'America/Juneau'=>'Alaska', 
  'Pacific/Honolulu'=>'Hawaii' 
);

$orgsapproved = array('N' => 'No', 'Y' => 'Yes');

$yesno = array('' => 'Select', 'N' => 'No', 'Y' => 'Yes');
$yes_or_no = array('N' => 'No', 'Y' => 'Yes');

$direct_indirect = array('D' => 'Direct Contact', 'I' => 'Indirect Contact');
$recruit_or_customer = array('R' => 'Recruit', 'C' => 'Customer');
$prospect_or_customer = array('P' => 'Prospect', 'C' => 'Customer');
$disposition = array('N'=>'Nothing',
					 'J'=>'Joined',
					 'B'=>'Bought',
					 'BR'=>'Bought & Referral Source',
					 'JB'=>'Joined & Bought',
					 'RS'=>'Referral Source');
//Credit Card Expiration Month
$expiremonth = array('' => '', '01' => '01', '02' => '02', '03' => '03', '04' => '04', '05' => '05',
			'06' => '06', '07' => '07', '08' => '08', '09' => '09', '10' => '10',
			'11' => '11', '12' => '12');

//CC Expiration Year
$expireyear = array('' => '', '2013' => '2013',
			'2014' => '2014', '2015' => '2015', '2016' => '2016', '2017' => '2017', '2018' => '2018',
			'2019' => '2019', '2020' => '2020', '2021' => '2021');

//Gender
$gender = array('' => 'Select', 'F' => 'Female', 'M' => 'Male');

$tier1steps = array('A' => 'No Initial Contact',
					'B' => '3x3 First Call Made',
					'C' => '3x3 Second Call Made',
					'D' => '3x3 Final Call Made',
					'H' => 'Contact Made',
					'E' => 'Contacted 25 Minute Video Sent',
					'F' => 'Follow-up After Video',
					'G' => 'Schedule Tier 2 Call');
$tier2steps = array('A' => 'Call Scheduled',
					'B' => 'Call Made',
					'C' => 'Contact Signed Up, Schedule Tier 3 Call',
					'D' => 'Tier 3 Call');
$tier3steps = array('A' => 'Call Scheduled',
					'B' => 'Call Completed',
					'C' => 'Fast Track',
					'D' => 'Traditional',
					'E' => 'Schedule Tier 4 Call',
					'F' => 'Missed Meeting');
$tier4steps = array('A' => 'Call Scheduled',
					'B' => 'Call Made',
					'C' => 'Policy Submitted',
					'D' => 'Policy Issued',
					'E' => 'Tiers Completed',
					'F' => 'Missed Meeting');
$contact_source = array('VFG' => 'VFG Pro',
					'FB' => 'Facebook',
					'CL' => 'Craigslist',
					'LI' => 'LinkedIn',
					'OTH' => 'Other');
$calendartime = array(''=>'Select',
					  '00:00' => 'Midnight (start of day)',
					  '00:30' => '12:30 am',
					  '01:00' => ' 1:00 am',
					  '01:30' => ' 1:30 am',
					  '02:00' => ' 2:00 am',
					  '02:30' => ' 2:30 am',
					  '03:00' => ' 3:00 am',
					  '03:30' => ' 3:30 am',
					  '04:00' => ' 4:00 am',
					  '04:30' => ' 4:30 am',
					  '05:00' => ' 5:00 am',
					  '05:30' => ' 5:30 am',
					  '06:00' => ' 6:00 am',
					  '06:30' => ' 6:30 am',
					  '07:00' => ' 7:00 am',
					  '07:30' => ' 7:30 am',
					  '08:00' => ' 8:00 am',
					  '08:30' => ' 8:30 am',
					  '09:00' => ' 9:00 am',
					  '09:30' => ' 9:30 am',
					  '10:00' => '10:00 am',
					  '10:30' => '10:30 am',
					  '11:00' => '11:00 am',
					  '11:30' => '11:30 am',
					  '12:00' => '12:00 pm',
					  '12:30' => '12:30 pm',
					  '13:00' => ' 1:00 pm',
					  '13:30' => ' 1:30 pm',
					  '14:00' => ' 2:00 pm',
					  '14:30' => ' 2:30 pm',
					  '15:00' => ' 3:00 pm',
					  '15:30' => ' 3:30 pm',
					  '16:00' => ' 4:00 pm',
					  '16:30' => ' 4:30 pm',
					  '17:00' => ' 5:00 pm',
					  '17:30' => ' 5:30 pm',
					  '18:00' => ' 6:00 pm',
					  '18:30' => ' 6:30 pm',
					  '19:00' => ' 7:00 pm',
					  '19:30' => ' 7:30 pm',
					  '20:00' => ' 8:00 pm',
					  '20:30' => ' 8:30 pm',
					  '21:00' => ' 9:00 pm',
					  '21:30' => ' 9:30 pm',
					  '22:00' => '10:00 pm',
					  '22:30' => '10:30 pm',
					  '23:00' => '11:00 pm',
					  '23:30' => '11:30 pm');
					  
//EMAIL TEMPLATE SETTINGS
$email_salutations = array(''=>'Select',
						'1'=>'Dear Friend',
						'2'=>'Dear Firstname',
						'3'=>'Greetings Friend',
						'4'=>'Greetings Firstname');

$email_closings = array(''=>'Select',
						'1'=>'Sincerely',
						'2'=>'Regards',
						'3'=>'Best Regards',
						'4'=>'Respectfully',
						'5'=>'Thank You');
$global_templates = array(''=>'Select',
						'1'=>'Template 1',
						'2'=>'Template 2');
$household_status = array(''=>'Select',
						  '1'=>'Breadwinner',
						  '2'=>'Spouse',
						  '3'=>'Dependant',
						  '4'=>'Other');
$policy_type = array(''=>'Select',
					'1'=>'Term LB',
					'2'=>'IUL',
					'3'=>'Other');
$carriers = array(''=>'Select',
				  '1'=>'TransAmerica',
				  '2'=>'WRL',
				  '3'=>'NationWide',
				  '4'=>'ING',
				  '5'=>'Pacific Life',
				  '6'=>'Other');

$event_hh = array(''=>'Select',
					'1' => ' 1 am',
					'2' => ' 2 am',
					'3' => ' 3 am',
					'4' => ' 4 am',
					'5' => ' 5 am',
					'6' => ' 6 am',
					'7' => ' 7 am',
					'8' => ' 8 am',
					'9' => ' 9 am',
					'10' => '10 am',
					'11' => '11 am',
					'12' => '12 pm',
					'13' => ' 1 pm',
					'14' => ' 2 pm',
					'15' => ' 3 pm',
					'16' => ' 4 pm',
					'17' => ' 5 pm',
					'18' => ' 6 pm',
					'19' => ' 7 pm',
					'20' => ' 8 pm',
					'21' => ' 9 pm',
					'22' => '10 pm',
					'23' => '11 pm',
					'24' => '12 am');
$meeting_hh = array(''=>'Select',
					'7' => ' 7 am',
					'8' => ' 8 am',
					'9' => ' 9 am',
					'10' => '10 am',
					'11' => '11 am',
					'12' => '12 pm',
					'13' => ' 1 pm',
					'14' => ' 2 pm',
					'15' => ' 3 pm',
					'16' => ' 4 pm',
					'17' => ' 5 pm',
					'18' => ' 6 pm',
					'19' => ' 7 pm',
					'20' => ' 8 pm',
					'21' => ' 9 pm',
					'22' => '10 pm');
$event_mm = array(''=>'Select',
					'00' => '00',
					'15' => '15',
					'30' => '30',
					'45' => '45');
$meeting_mm = array('00' => '00',
					'15' => '15',
					'30' => '30',
					'45' => '45');
$notification_int = array(''=>'None',
					'15' => '15 minutes',
					'30' => '30 minutes',
					'45' => '45 minutes',
					'60' => '60 minutes');
$vfgid_type = array('T' => 'Temporary VFGID', 
					'P' => 'Permanent VFGID');
$lead_priority = array(''=>'Select',
					'1' => '1',
					'2' => '2',
					'3' => '3',
					'4' => '4',
					'5' => '5');
$lead_type = array(''=>'Select',
					'1' => 'Relative',
					'2' => 'Friend',
					'3' => 'Acquaintance',
					'4' => 'Referral',
					'5' => 'Cold');
$lead_profile = array(''=>'Select',
					'1' => '25+ Years',
					'2' => 'Married',
					'3' => 'Children',
					'4' => 'Home Owner',
					'5' => 'Solid Business Background',
					'6' => 'Income',
					'7' => 'Dissatisfied',
					'8' => 'Entrepreneurial');
$lead_category = array('' => 'Select',
					'Accountant' => 'Accountant', 
					'Air Force' => 'Air Force', 
					'Air Traffic Controller' => 'Air Traffic Controller', 
					'Ambulance Driver' => 'Ambulance Driver', 
					'Animal Trainer' => 'Animal Trainer', 
					'Antiques Dealer' => 'Antiques Dealer', 
					'Appliance Salesperson' => 'Appliance Salesperson', 
					'Architect' => 'Architect', 
					'Armored Car Driver' => 'Armored Car Driver', 
					'Army' => 'Army', 
					'Auctioneer' => 'Auctioneer', 
					'Aunt' => 'Aunt', 
					'Auto Mechanic' => 'Auto Mechanic', 
					'Auto Repairman' => 'Auto Repairman', 
					'Auto Supply Salesman' => 'Auto Supply Salesman', 
					'Babysitter' => 'Babysitter', 
					'Baker' => 'Baker', 
					'Bank Teller' => 'Bank Teller', 
					'Banker' => 'Banker', 
					'Barber' => 'Barber', 
					'Baseball Player' => 'Baseball Player', 
					'Beautician' => 'Beautician', 
					'Best Friend' => 'Best Friend', 
					'Best Man' => 'Best Man', 
					'Bookworm' => 'Bookworm', 
					'Boss' => 'Boss', 
					'Bowler' => 'Bowler', 
					'Bridesmaids' => 'Bridesmaids', 
					'Brother' => 'Brother', 
					'Brothers In-Laws' => 'Brothers In-Laws', 
					'Brother-In-Law' => 'Brother-In-Law', 
					'Bus Driver' => 'Bus Driver', 
					'Cabinetmaker' => 'Cabinetmaker', 
					'Cable TV Repairman' => 'Cable TV Repairman', 
					'Camper' => 'Camper', 
					'Car Pool' => 'Car Pool', 
					'Car Salesman' => 'Car Salesman', 
					'Carpenter' => 'Carpenter', 
					'Carpet Cleaners' => 'Carpet Cleaners', 
					'Carpet Layer' => 'Carpet Layer', 
					'Cashier' => 'Cashier', 
					'Cat Lover' => 'Cat Lover', 
					'Caterer' => 'Caterer', 
					'Cell Phone Contact' => 'Cell Phone Contact', 
					'Chamber of Commerce' => 'Chamber of Commerce', 
					'Chef' => 'Chef', 
					'Chiropractor' => 'Chiropractor', 
					'Civic Club' => 'Civic Club', 
					'Clergyman' => 'Clergyman', 
					'Coach' => 'Coach', 
					'Coast Guard' => 'Coast Guard', 
					'Coffee Shop' => 'Coffee Shop', 
					'Competitor' => 'Competitor', 
					'Complainer' => 'Complainer', 
					'Computer Gamer' => 'Computer Gamer', 
					'Computer Programmer' => 'Computer Programmer', 
					'Computer Sales' => 'Computer Sales', 
					'Computer Technician' => 'Computer Technician', 
					'Computer Whiz' => 'Computer Whiz', 
					'Contractor' => 'Contractor', 
					'Convenience Store Employee' => 'Convenience Store Employee', 
					'Cook ' => 'Cook ', 
					'Cosmetics Salesperson' => 'Cosmetics Salesperson', 
					'Cousin' => 'Cousin', 
					'Coworker' => 'Coworker', 
					'Credit Union Employee' => 'Credit Union Employee', 
					'Customer' => 'Customer', 
					'Dance Teacher' => 'Dance Teacher', 
					'Dart Player' => 'Dart Player', 
					'Delivery Person' => 'Delivery Person', 
					'Den Leader' => 'Den Leader', 
					'Dentist' => 'Dentist', 
					'Department Store Employee' => 'Department Store Employee', 
					'Direct Sales' => 'Direct Sales', 
					'Dishwasher' => 'Dishwasher', 
					'Doctor' => 'Doctor', 
					'Dog Lover' => 'Dog Lover', 
					'Doll Maker' => 'Doll Maker', 
					'Dry Cleaner' => 'Dry Cleaner', 
					'Editor' => 'Editor', 
					'Electrician' => 'Electrician', 
					'Electronics Store Employee' => 'Electronics Store Employee', 
					'Elks Club' => 'Elks Club', 
					'Email Contact' => 'Email Contact', 
					'Engineer' => 'Engineer', 
					'Enjoys Karate' => 'Enjoys Karate', 
					'Executive Assistant' => 'Executive Assistant', 
					'Express Mail Person' => 'Express Mail Person', 
					'Eye Center Employee' => 'Eye Center Employee', 
					'Farmer' => 'Farmer', 
					'Father' => 'Father', 
					'Father-In-Law' => 'Father-In-Law', 
					'Fellow Church Members' => 'Fellow Church Members', 
					'Fire Chief' => 'Fire Chief', 
					'Fireman' => 'Fireman', 
					'Fisherman' => 'Fisherman', 
					'Flight Attendant' => 'Flight Attendant', 
					'Flower Shop Employee' => 'Flower Shop Employee', 
					'Football Player' => 'Football Player', 
					'Friends of Parents' => 'Friends of Parents', 
					'Fundraiser' => 'Fundraiser', 
					'Funeral Director' => 'Funeral Director', 
					'Furniture Repairman' => 'Furniture Repairman', 
					'Game Warden' => 'Game Warden', 
					'Golfer' => 'Golfer', 
					'Grandfather' => 'Grandfather', 
					'Grandmother' => 'Grandmother', 
					'Graphic Designer' => 'Graphic Designer', 
					'Grocery Store Employee' => 'Grocery Store Employee', 
					'Guidance Counselor' => 'Guidance Counselor', 
					'Handball Player' => 'Handball Player', 
					'Hang Glider' => 'Hang Glider', 
					'Hardware Store Employee' => 'Hardware Store Employee', 
					'Health Food Shop' => 'Health Food Shop', 
					'Health Spa Employee' => 'Health Spa Employee', 
					'Highway Dept Employee' => 'Highway Dept Employee', 
					'Highway Patrolman' => 'Highway Patrolman', 
					'Hiker' => 'Hiker', 
					'Home Builder' => 'Home Builder', 
					'Home Siding Salesperson' => 'Home Siding Salesperson', 
					'Hospital Worker' => 'Hospital Worker', 
					'Hotel Employee' => 'Hotel Employee', 
					'Hunter' => 'Hunter', 
					'Inspector' => 'Inspector', 
					'Insulator' => 'Insulator', 
					'Jaycees' => 'Jaycees', 
					'Job-hunting friend' => 'Job-hunting friend', 
					'Jogger' => 'Jogger', 
					'Journalist' => 'Journalist', 
					'Kiwanis' => 'Kiwanis', 
					'Landlord' => 'Landlord', 
					'Landscaper' => 'Landscaper', 
					'Lawn Maintenance' => 'Lawn Maintenance', 
					'Lawyer' => 'Lawyer', 
					'Librarian' => 'Librarian', 
					'Likable Person' => 'Likable Person', 
					'Lions Club' => 'Lions Club', 
					'Locksmith' => 'Locksmith', 
					'Lunch Friend' => 'Lunch Friend', 
					'Machine Shop Employee' => 'Machine Shop Employee', 
					'Maid of Honor' => 'Maid of Honor', 
					'Mailman' => 'Mailman', 
					'Manager' => 'Manager', 
					'Marines' => 'Marines', 
					'Masons' => 'Masons', 
					'Matron of Honor' => 'Matron of Honor', 
					'Mother' => 'Mother', 
					'Mother-In-Law' => 'Mother-In-Law', 
					'Mountain Climber' => 'Mountain Climber', 
					'Movers/Shakers' => 'Movers/Shakers', 
					'Music Teacher' => 'Music Teacher', 
					'National Guard' => 'National Guard', 
					'Navy' => 'Navy', 
					'Neice' => 'Neice', 
					'Neighbor' => 'Neighbor', 
					'Nephew' => 'Nephew', 
					'Notary' => 'Notary', 
					'Nurse' => 'Nurse', 
					'Office Supplies Salesman' => 'Office Supplies Salesman', 
					'Orthodontist' => 'Orthodontist', 
					'Painter' => 'Painter', 
					'Parents Neighbor' => 'Parents Neighbor', 
					'Parking Attendant' => 'Parking Attendant', 
					'Partner' => 'Partner', 
					'Payroll Clerk' => 'Payroll Clerk', 
					'Pension Plan Manager' => 'Pension Plan Manager', 
					'Personnel Manager' => 'Personnel Manager', 
					'Pest Control' => 'Pest Control', 
					'Pharmacist' => 'Pharmacist', 
					'Phone Installer' => 'Phone Installer', 
					'Photographer' => 'Photographer', 
					'Piano Teacher' => 'Piano Teacher', 
					'Piano Tuner' => 'Piano Tuner', 
					'Pilot' => 'Pilot', 
					'Plays Bingo' => 'Plays Bingo', 
					'Plays Bridge' => 'Plays Bridge', 
					'Plays Pool' => 'Plays Pool', 
					'Plays Table Tennis' => 'Plays Table Tennis', 
					'Plumber' => 'Plumber', 
					'Policeman' => 'Policeman', 
					'Principal' => 'Principal', 
					'Printer' => 'Printer', 
					'Professor' => 'Professor', 
					'Publisher' => 'Publisher', 
					'Racquetball Player' => 'Racquetball Player', 
					'Radio Announcer' => 'Radio Announcer', 
					'Railroad Conductor/Worker' => 'Railroad Conductor/Worker', 
					'Realtor' => 'Realtor', 
					'Repairman' => 'Repairman', 
					'Restaurant Owner' => 'Restaurant Owner', 
					'Roofer' => 'Roofer', 
					'Salesperson' => 'Salesperson', 
					'Satellite TV Serviceman' => 'Satellite TV Serviceman', 
					'Scoutmaster' => 'Scoutmaster', 
					'Seamstress' => 'Seamstress', 
					'Security Guard' => 'Security Guard', 
					'Seeking a part-time job' => 'Seeking a part-time job', 
					'Sister' => 'Sister', 
					'Sisters In-Laws' => 'Sisters In-Laws', 
					'Sister-In-Law' => 'Sister-In-Law', 
					'Skier' => 'Skier', 
					'Soccer Player' => 'Soccer Player', 
					'Social Worker' => 'Social Worker', 
					'Softball Player' => 'Softball Player', 
					'Software Programmer' => 'Software Programmer', 
					'Someone who almost lost a job' => 'Someone who almost lost a job', 
					'Someone who hates their job' => 'Someone who hates their job', 
					'Someone who hates to lose' => 'Someone who hates to lose', 
					'Someone who lost a job' => 'Someone who lost a job', 
					'Someone who was not promoted' => 'Someone who was not promoted', 
					'Sportscaster' => 'Sportscaster', 
					'Spouses Best Friend' => 'Spouses Best Friend', 
					'Substitute Teacher' => 'Substitute Teacher', 
					'Sunday School Teacher' => 'Sunday School Teacher', 
					'Supervisor' => 'Supervisor', 
					'Surgeon' => 'Surgeon', 
					'Surveyor' => 'Surveyor', 
					'Swimmer' => 'Swimmer', 
					'Tanning Salon Employee' => 'Tanning Salon Employee', 
					'Teacher' => 'Teacher', 
					'Teacher' => 'Teacher', 
					'Tennis Player' => 'Tennis Player', 
					'Therapist' => 'Therapist', 
					'Tire Store Employee' => 'Tire Store Employee', 
					'Travel Agent' => 'Travel Agent', 
					'Tree Surgeon' => 'Tree Surgeon', 
					'Truck Driver' => 'Truck Driver', 
					'TV Repairman' => 'TV Repairman', 
					'Uncle' => 'Uncle', 
					'Union Member' => 'Union Member', 
					'Upholsterer' => 'Upholsterer', 
					'Ushers' => 'Ushers', 
					'Vending Salesman' => 'Vending Salesman', 
					'Veterinarian' => 'Veterinarian', 
					'VFW' => 'VFW', 
					'Waiter' => 'Waiter', 
					'Waitress' => 'Waitress', 
					'Walking Encyclopedia' => 'Walking Encyclopedia', 
					'Writer' => 'Writer', 
					'Youth Director' => 'Youth Director',
					'Other' => 'Other');
?>